/* SPDX-License-Identifier: GPL-2.0-only */

#define CONFIG_DRM_MSM 1
#define CONFIG_DRM_MSM_SDE 1
#define CONFIG_SYNC_FILE 1
#define CONFIG_DRM_MSM_DSI 1
#define CONFIG_DSI_PARSER 1
#define CONFIG_DRM_SDE_WB 1
#define CONFIG_QCOM_MDSS_PLL 1
#define CONFIG_MSM_SDE_ROTATOR 1
#define CONFIG_DRM_SDE_RSC 1
#define CONFIG_DRM_SDE_SPECIFIC_PANEL 1
#define CONFIG_DRM_MSM_DSI_SOMC_PANEL 1
#define CONFIG_SOMC_PANEL_INCELL 1
